-- 0026_add_auth_columns_to_users.sql
-- Add OAuth and authentication related columns
ALTER TABLE users 
  ADD COLUMN IF NOT EXISTS google_id STRING,
  ADD COLUMN IF NOT EXISTS name STRING,
  ADD COLUMN IF NOT EXISTS picture STRING,
  ADD COLUMN IF NOT EXISTS access_token STRING,
  ADD COLUMN IF NOT EXISTS refresh_token STRING,
  ADD COLUMN IF NOT EXISTS token_expiry TIMESTAMP,
  ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS login_count LONG DEFAULT 0,
  ADD COLUMN IF NOT EXISTS locale STRING,
  ADD COLUMN IF NOT EXISTS hd STRING,
  ADD COLUMN IF NOT EXISTS auth_provider STRING DEFAULT 'google',
  ADD COLUMN IF NOT EXISTS current_sign_in_ip STRING,
  ADD COLUMN IF NOT EXISTS last_sign_in_ip STRING,
  ADD COLUMN IF NOT EXISTS sign_in_count LONG DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tos_accepted_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS email_verified BOOLEAN DEFAULT false;
